name: Publish Docker image to GitHub Package Registry
on: push
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:

    - name: Copy Repo Files
      uses: actions/checkout@master

     #This Action Emits 2 Variables, IMAGE_SHA_NAME and IMAGE_URL 
     #which you can reference in subsequent steps
    - name: Publish Docker Image to GPR
      uses: machine-learning-apps/gpr-docker-publish@master
      id: docker
      with:
        USERNAME: trashhalo
        PASSWORD: ${{ secrets.GITHUB_TOKEN  }}
        IMAGE_NAME: 'ssb-room'
        DOCKERFILE_PATH: 'Dockerfile'
        BUILD_CONTEXT: '.'